### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by jamesclark6871** [jamesclark6871/prework-study-guide#1]
# HTML

## User Story
As a bootcamp student
I want the prework notes to be structured on a webpage
so that I can easily find and read information

## Aceptance Criteria
GIVEN a Prework Study Guide Website
WHEN I visit the website in my browser
THEN I see four boxes titled HTML, CSS, Git, JavaScript with associated notes listed

**Comment by Prakashd20** [comment]
I would like to engage for the above mentioned acceptance criteria as I have required knowledge to both css and js to full fledged your requirements, looking forward to work for the same.
